name: test handler

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8 #3.7?
      - uses: actions/checkout@v2
      - run: python test.py
